### ISSUE TITLE
Error on countdown for seconds

### ISSUE THREAD

**Issue by gblanc** [miguelmota/clock-timer#1]
Hi,

There is error on code to compute reminding seconds for countdown : 
Code is  ;
` this.settings.seconds = ( Math.floor( this.settings.now % 60 ) );`

and should be : 
`this.settings.seconds = ( 60 - Math.floor( ( ( ( this.settings.endDate - this.settings.now ) % 86400 ) % 3600) / 3660 ) );`
         
I have not down a PR for this, but you can change code.

Regards,

greg

**Comment by miguelmota** [comment]
Hi,
Can you show/explain what you're expecting and what the actual result is?
Just trying to understand your proposed solution.
Thanks
